# name: update database
# on:
#   schedule:
#     - cron: "0 6 * * *"
# jobs:
#   updatedb:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Set up Python 3.x
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.12
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           python -m pip install -r requirements.txt
#       - name: run update
#         run: |
#           python ./databruce/insert_data.py
          # somehow set database url to arg? heroku vs local?
          # should set it to heroku and updates go there immediately, can pull locally later using backup
          # also create db dump file as daily backup, can restore local from there.
